imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
            secured_area:
                pattern:    ^/admin
                http_basic:

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: info
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

