<?php

namespace Elmet\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CurtainColourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurtainColourRepository extends EntityRepository
{
    public function findOneByNameJoinedToDesignByUrlName($colourName, $urlName)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT cc, cd FROM ElmetSiteBundle:CurtainColour cc
                                    JOIN cc.curtain_design cd
                                    WHERE cc.name = :name
                                    and cd.url_name = :urlName');
        
        $query->setParameter('name',$colourName);
        $query->setParameter('urlName',$urlName);
    
        try {
                return $query->getSingleResult();
        }
        catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findByColourId($colourId)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT cc FROM ElmetSiteBundle:CurtainColour cc
                                    WHERE cc.id = :id');
        
        $query->setParameter('id',$colourId);
        
        return $query->getSingleResult();
    }
}
        