ElmetAdminBundle_homepage:
    pattern:  /
    defaults: { _controller: ElmetAdminBundle:Home:index }

ElmetAdminBundle_login_page:
    pattern:  /login
    defaults: { _controller: ElmetAdminBundle:Security:login }
    
ElmetAdminBundle_login_check_page:
    pattern:  /login/check
    defaults: { _controller: ElmetAdminBundle:Security:check }

ElmetAdminBundle_cepb_view_page:
    pattern:  /curtaineyeletpriceband/view
    defaults: { _controller: ElmetAdminBundle:CurtainEyeletPriceBand:view }

ElmetAdminBundle_cepb_update_page:
    pattern:  /curtaineyeletpriceband/update
    defaults: { _controller: ElmetAdminBundle:CurtainEyeletPriceBand:update }

ElmetAdminBundle_cepb_remove_page:
    pattern:  /curtaineyeletpriceband/remove/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainEyeletPriceBand:remove }

ElmetAdminBundle_testimonial_view_page:
    pattern:  /testimonial/view
    defaults: { _controller: ElmetAdminBundle:Testimonial:view }

ElmetAdminBundle_testimonial_update_page:
    pattern:  /testimonial/update
    defaults: { _controller: ElmetAdminBundle:Testimonial:update }

ElmetAdminBundle_testimonial_remove_page:
    pattern:  /testimonial/remove/{id}
    defaults: { _controller: ElmetAdminBundle:Testimonial:remove }

ElmetAdminBundle_pelmet_view_page:
    pattern:  /pelmet/view
    defaults: { _controller: ElmetAdminBundle:Pelmet:view }

ElmetAdminBundle_pelmet_update_page:
    pattern:  /pelmet/update
    defaults: { _controller: ElmetAdminBundle:Pelmet:update }

ElmetAdminBundle_pelmet_remove_page:
    pattern:  /pelmet/remove/{id}
    defaults: { _controller: ElmetAdminBundle:Pelmet:remove }

ElmetAdminBundle_ccover_view_page:
    pattern:  /cushioncover/view
    defaults: { _controller: ElmetAdminBundle:CushionCover:view }

ElmetAdminBundle_ccover_update_page:
    pattern:  /cushioncover/update
    defaults: { _controller: ElmetAdminBundle:CushionCover:update }

ElmetAdminBundle_ccover_remove_page:
    pattern:  /cushioncover/remove/{id}
    defaults: { _controller: ElmetAdminBundle:CushionCover:remove }
    
ElmetAdminBundle_tieback_view_page:
    pattern:  /tieback/view
    defaults: { _controller: ElmetAdminBundle:TieBack:view }

ElmetAdminBundle_tieback_update_page:
    pattern:  /tieback/update
    defaults: { _controller: ElmetAdminBundle:TieBack:update }

ElmetAdminBundle_tieback_remove_page:
    pattern:  /tieback/remove/{id}
    defaults: { _controller: ElmetAdminBundle:TieBack:remove }

ElmetAdminBundle_fabric_view_page:
    pattern:  /fabric/view
    defaults: { _controller: ElmetAdminBundle:Fabric:view }

ElmetAdminBundle_fabric_update_page:
    pattern:  /fabric/update
    defaults: { _controller: ElmetAdminBundle:Fabric:update }

ElmetAdminBundle_fabric_remove_page:
    pattern:  /fabric/remove/{id}
    defaults: { _controller: ElmetAdminBundle:Fabric:remove }
    
ElmetAdminBundle_cpb_view_page:
    pattern:  /curtainpriceband/view
    defaults: { _controller: ElmetAdminBundle:CurtainPriceBand:view }

ElmetAdminBundle_cpb_update_page:
    pattern:  /curtainpriceband/update
    defaults: { _controller: ElmetAdminBundle:CurtainPriceBand:update }

ElmetAdminBundle_cpb_remove_page:
    pattern:  /curtainpriceband/remove/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainPriceBand:remove }

ElmetAdminBundle_cp_view_page:
    pattern:  /curtainprice/view
    defaults: { _controller: ElmetAdminBundle:CurtainPrice:view }

ElmetAdminBundle_cp_index_page:
    pattern:  /curtainprice/index
    defaults: { _controller: ElmetAdminBundle:CurtainPrice:index }

ElmetAdminBundle_cp_update_page:
    pattern:  /curtainprice/update
    defaults: { _controller: ElmetAdminBundle:CurtainPrice:update }

ElmetAdminBundle_cp_remove_page:
    pattern:  /curtainprice/remove/{id}/{priceBandId}
    defaults: { _controller: ElmetAdminBundle:CurtainPrice:remove }

ElmetAdminBundle_cp_view_page:
    pattern:  /curtainprice/view/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainPrice:view }

ElmetAdminBundle_cd_index_page:
    pattern:  /curtaindesign/index
    defaults: { _controller: ElmetAdminBundle:CurtainDesign:index }

ElmetAdminBundle_cd_view_page:
    pattern:  /curtaindesign/view/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainDesign:view }

ElmetAdminBundle_cd_remove_page:
    pattern:  /curtaindesign/remove/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainDesign:remove }

ElmetAdminBundle_cd_update_page:
    pattern:  /curtaindesign/update
    defaults: { _controller: ElmetAdminBundle:CurtainDesign:update }

ElmetAdminBundle_cd_new_page:
    pattern:  /curtaindesign/new
    defaults: { _controller: ElmetAdminBundle:CurtainDesign:new }
    
ElmetAdminBundle_cd_create_page:
    pattern:  /curtaindesign/create
    defaults: { _controller: ElmetAdminBundle:CurtainDesign:create }

ElmetAdminBundle_cc_view_page:
    pattern:  /curtaincolour/view/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainColour:view }

ElmetAdminBundle_cc_remove_page:
    pattern:  /curtaincolour/remove/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainColour:remove }

ElmetAdminBundle_cc_update_page:
    pattern:  /curtaincolour/update
    defaults: { _controller: ElmetAdminBundle:CurtainColour:update }

ElmetAdminBundle_cc_new_page:
    pattern:  /curtaincolour/new/{id}
    defaults: { _controller: ElmetAdminBundle:CurtainColour:new }
    
ElmetAdminBundle_cc_create_page:
    pattern:  /curtaincolour/create
    defaults: { _controller: ElmetAdminBundle:CurtainColour:create }

ElmetAdminBundle_order_search_page:
    pattern:  /order/search
    defaults: { _controller: ElmetAdminBundle:Order:search }

ElmetAdminBundle_order_results_page:
    pattern:  /order/results
    defaults: { _controller: ElmetAdminBundle:Order:results }

ElmetAdminBundle_order_details_page:
    pattern:  /order/details/{id}
    defaults: { _controller: ElmetAdminBundle:Order:details } 
 
ElmetAdminBundle_stock_view_page:
    pattern:  /curtainstock/view
    defaults: { _controller: ElmetAdminBundle:CurtainStock:view }

ElmetAdminBundle_stock_update_page:
    pattern:  /curtainstock/update
    defaults: { _controller: ElmetAdminBundle:CurtainStock:update }

ElmetAdminBundle_order_tracking_view_page:
    pattern:  /ordertracking/view
    defaults: { _controller: ElmetAdminBundle:OrderTracking:view }

ElmetAdminBundle_order_tracking_details_page:
    pattern:  /ordertracking/details/{id}
    defaults: { _controller: ElmetAdminBundle:OrderTracking:details }

ElmetAdminBundle_order_tracking_email_page:
    pattern:  /ordertracking/email/{id}
    defaults: { _controller: ElmetAdminBundle:OrderTracking:email }

ElmetAdminBundle_order_tracking_message_page:
    pattern:  /ordertracking/message/{id}
    defaults: { _controller: ElmetAdminBundle:OrderTracking:message }

ElmetAdminBundle_order_tracking_update_page:
    pattern:  /ordertracking/update
    defaults: { _controller: ElmetAdminBundle:OrderTracking:update }
    
ElmetAdminBundle_order_tracking_message_page:
    pattern:  /ordertracking/message/{id}
    defaults: { _controller: ElmetAdminBundle:OrderTracking:message }

ElmetAdminBundle_order_tracking_send_page:
    pattern:  /ordertracking/send
    defaults: { _controller: ElmetAdminBundle:OrderTracking:send }

ElmetAdminBundle_order_tracking_cancel_page:
    pattern:  /ordertracking/cancel/{id}
    defaults: { _controller: ElmetAdminBundle:OrderTracking:cancel }

ElmetAdminBundle_order_tracking_worksheet_page:
    pattern:  /ordertracking/worksheet/{type}
    defaults: { _controller: ElmetAdminBundle:OrderTracking:worksheet }